theme: osuny
_merge: deep
params:
  keycdn:
    url: https://osunystaging-1b4da.kxcdn.com
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
